language: cpp
compiler: gcc

env:
  global:
    - CBANG_HOME=$PWD/cbang
    - CHAKRA_CORE_HOME=$PWD/ChakraCore

  matrix:
    - DEBUG_BUILD=1
    - DEBUG_BUILD=0

before_install:
  - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com EC4926EA
  - echo echo "deb http://archive.ubuntu.com/ubuntu/ precise-updates multiverse" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y libunwind8-dev

before_script:
  - git clone --depth=1 https://github.com/CauldronDevelopmentLLC/ChakraCore.git
  - git clone --depth=1 https://github.com/CauldronDevelopmentLLC/cbang.git

script:
  - cd ChakraCore; ./build.sh --static -j 8
  - mkdir tmp
  - cd tmp; for i in $(find ../ChakraCore/Build* -name \*.a); do ar x $i; done
  - ar rcs ChakraCore/libChakraCore.a tmp/*.o
  - scons -C cbang debug=$DEBUG_BUILD -j 8
  - scons debug=$DEBUG_BUILD -j 8

addons:
  apt:
    packages:
      - git
      - scons
      - libbz2-dev
      - zlib1g-dev
      - libexpat1-dev
      - libboost-iostreams-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-regex-dev
      - libsqlite3-dev
      - libicu-dev
      - qt4-dev-tools
      - libqt4-dev
      - libqt4-opengl-dev
      - libcairo2-dev
      - libfreetype6-dev
