language: cpp
compiler: gcc
dist: trusty
sudo: false

env:
  global:
    - CBANG_HOME=$PWD/cbang
    - CHAKRA_CORE_HOME=$PWD/ChakraCore

  matrix:
    - DEBUG_BUILD=1
    - DEBUG_BUILD=0

install:
  - sudo apt-get update
  - sudo apt-get install -y qt4-dev-tools libunwind8-dev

before_script:
  - git clone --depth=1 https://github.com/CauldronDevelopmentLLC/ChakraCore.git
  - git clone --depth=1 https://github.com/CauldronDevelopmentLLC/cbang.git

script:
  - cd ChakraCore; ./build.sh --static -j 8
  - mkdir tmp
  - cd tmp; for i in $(find ../ChakraCore/Build* -name \*.a); do ar x $i; done
  - ar rcs ChakraCore/libChakraCore.a tmp/*.o
  - scons -C cbang debug=$DEBUG_BUILD -j 8
  - scons debug=$DEBUG_BUILD -j 8

addons:
  apt:
    packages:
      - git
      - clang
      - scons
      - libbz2-dev
      - zlib1g-dev
      - libexpat1-dev
      - libboost-iostreams-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-regex-dev
      - libsqlite3-dev
      - libicu-dev
      - libqt4-dev
      - libqt4-opengl-dev
      - libcairo2-dev
      - libfreetype6-dev
