language: cpp
compiler: gcc
dist: xenial

env:
  global:
    - CBANG_HOME=$PWD/cbang

  matrix:
    - DEBUG_BUILD=1
    - DEBUG_BUILD=0

before_script:
  - git clone --depth=1 https://github.com/CauldronDevelopmentLLC/cbang.git

script:
  - scons -C cbang debug=$DEBUG_BUILD -j 8
  - scons debug=$DEBUG_BUILD -j 8

addons:
  apt:
    packages:
      - git
      - scons
      - libv8-dev
      - qt5-default
      - libqt5websockets5-dev
      - libqt5opengl5-dev
